trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
# Set up Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

# Build the .NET project
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure for Students(13a04823-0498-4860-814d-7e6581359b65)'
    command: 'build'

# Run a one-line script
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Run a multi-line script
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Run the .NET project
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure for Students(13a04823-0498-4860-814d-7e6581359b65)'
    command: 'run'
